### PR TITLE
Feature/search filter

### PR DESCRIPTION
**Pull request by ViMuilu**
### Description

Added filter to search results. Note changes to backend as well.

### Related issues
#153 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

Changes mainly to Beaconresults.vue. Added a list of filters and two new functions getFilteringTerms and filterResults
Cypress tests for this feature.

### Testing

- [x] Integration Tests

### CODE REVIEW

**Comment by ViMuilu** [comment]
Tests should pass when the backend is merged to dev

**Comment by teemukataja** [comment]
rebased branch on `dev` to get CI to run again

**Comment by teemukataja** [comment]
cypress tests need updating

**Comment by ViMuilu** [comment]
Not sure why but eslint wanted to lint all files.

**Comment by ViMuilu** [comment]
> Not sure why but eslint wanted to lint all files.

Test fail now because of this

**Review by teemukataja — APPROVED** [review]

**Pull request merged**
